image: maven:3.6.2-jdk-8

cache:
  paths:
    - .m2/
  # keep cache across branch
  key: "$CI_PROJECT_ID"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2"

stages:
  - build

compile-test:
  stage: build
  script:
    - "mvn clean verify --batch-mode"
  artifacts:
    reports:
      junit:
        - "*/target/surefire-reports/TEST-*.xml"