/*-
 * ========================LICENSE_START=================================
 * NavExt Runtime
 * %%
 * Copyright (C) 2019 - 2026 4Soft GmbH
 * %%
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * =========================LICENSE_END==================================
 */
package com.foursoft.harness.navext.runtime.postprocessing;

import com.foursoft.harness.navext.runtime.annotations.XmlBackReference;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

class BackReferencePropertyHandlerTest {

    @Test
    void createsTheBackReferenceSetWhenTheFieldIsStillNull() {
        final LazyTarget target = new LazyTarget();
        final Source source = new Source(target);

        handler().handleObject(source);

        assertThat(target.referencedBy).containsExactly(source);
    }

    @Test
    void fillsAnEagerlyInitialisedBackReferenceSet() {
        final EagerTarget target = new EagerTarget();
        final Source source = new Source(target);

        handler().handleObject(source);

        assertThat(target.referencedBy).containsExactly(source);
    }

    @Test
    void keepsTheSetItCreatedForFurtherBackReferences() {
        final LazyTarget target = new LazyTarget();
        final Source firstSource = new Source(target);
        final Source secondSource = new Source(target);

        handler().handleObject(firstSource);
        final Set<Object> setAfterFirstReference = target.referencedBy;
        handler().handleObject(secondSource);

        assertThat(target.referencedBy)
                .isSameAs(setAfterFirstReference)
                .containsExactlyInAnyOrder(firstSource, secondSource);
    }

    private BackReferencePropertyHandler handler() {
        return new BackReferencePropertyHandler(sourceField());
    }

    private Field sourceField() {
        try {
            return Source.class.getDeclaredField("targets");
        } catch (final NoSuchFieldException e) {
            throw new IllegalStateException(e);
        }
    }

    private static class Source {

        @XmlBackReference(destinationField = "referencedBy")
        private final List<Object> targets;

        Source(final Object target) {
            targets = List.of(target);
        }

    }

    /**
     * A back-reference field as the XJC plugin generates it: initialized on first access by the getter.
     */
    private static class LazyTarget {

        private Set<Object> referencedBy;

    }

    /**
     * A back-reference field as models generated by older versions of the XJC plugin declare it.
     */
    private static class EagerTarget {

        private final Set<Object> referencedBy = new HashSet<>();

    }

}
