name: Release Version

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The Version of the Release (e.g. 0.1.0)'
        required: false
        default: ''
      github_user:
        description: 'The GitHub user to release with (Owner of the PAT)'
        required: true
        default: 'RainerGanss'
      github_pat:
        description: 'A PAT that has the permission to push to protected branches.'
        required: true
      git_name:
        description: 'Name used for the release commits.'
        required: true
        default: 'Rainer Ganß'
      git_mail:
        description: 'eMail used for the release commits.'
        required: true
        default: 'ganss@4soft.de'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'adopt'
          java-version: '17'
          check-latest: true
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
      - name: Configure Git user
        run: |
          git config user.email "${{ github.event.inputs.git_mail }}"
          git config user.name "${{ github.event.inputs.git_name }}"
          git remote set-url origin https://${{ github.event.inputs.github_user }}:${{ github.event.inputs.github_pat }}@github.com/${GITHUB_REPOSITORY}.git
      - name: Release with Maven
        run: |
          ./mvnw -e -P release -B -DreleaseVersion=${{ github.event.inputs.release_version }} -s .mvn/release.settings.xml gitflow:release --file pom.xml
        env:
          SONATYPE_CENTRAL_USERNAME: ${{ secrets.SONATYPE_CENTRAL_USERNAME }}
          SONATYPE_CENTRAL_TOKEN:    ${{ secrets.SONATYPE_CENTRAL_TOKEN }}
          GPG_PASSPHRASE:   ${{ secrets.GPG_PASSPHRASE }}
